config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  resources :tickets
  resources :lots do
    resources :events
  end
  resources :cars
  
  get 'billings/pre_pay', to:'billings#pre_pay', as: 'pre_pay_billings'
  get 'billings/execute', to:'billings#execute', as:'execute_billings'
  
  root 'tickets#new'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :lot
  belongs_to :ticket
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :get_lot
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @events = @lot.events
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @event = @lot.events.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @event = @lot.events.build(event_params)

        respond_to do |format|
         if @event.save  
            format.html { redirect_to lot_events_path(@lot), notice: 'Post was successfully created.' }
            format.json { render :show, status: :created, location: @event }
         else
            format.html { render :new }
            format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        byebug
        format.html { redirect_to lot_event_path(@lot), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to lot_events_path(@lot), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private

    def get_lot
      @lot = Lot.find(params[:lot_id])
    end
    
    def set_event
      @event = @lot.events.find(params[:id])  
    end

    def event_params
      params.require(:event).permit(:lot_id, :date_parking_start, :date_parking_end, :ticket_id)
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_events_fields.html.erb
  <div class="row my-4">
    <div class="form-group col-md-3">
      <%= events_form.text_field :date_parking_start , id: 'init_date_picker',placeholder:"Fecha de Inicio" %>
    </div>
    <div class="form-group col-md-3">
      <%= events_form.text_field :date_parking_end , id: 'end_date_picker',placeholder:"Fecha de Salida"%>
    </div>
  </div>

  <%= events_form.label :lot_id %>
  <%= events_form.collection_select(:lot_id, Lot.all, :val_lot, :parking_lot, {:class => 'lot_id'})%>

app/views/events/_form.html.erb
<%= form_with model: [:lot, @event] do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lot_event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
    <%= form.label :lot_id %>
    <%= form.text_field :lot_id %>
  </div> -->

  <div class="field">
    <%= form.label :date_parking_start %>
    <%= form.text_field :date_parking_start, id: "init_date_picker" , class: 'datepicker'%>
  </div>

  <div class="field">
    <%= form.label :date_parking_end %>
    <%= form.text_field :date_parking_end, id: "end_date_picker" , class: 'datepicker' %>
  </div>

  <div class="field">
    <%= form.label :car_id %>
    <%= form.select :car_id, options_for_select(current_user.cars.map{|s|[s.plate,s.id]}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', lot_events_path %> |
<%= link_to 'Back', lot_events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>
<div class="container">

  <table>
    <thead>
      <tr>
        <th>Ubicacion</th>
        <th>Date parking start</th>
        <th>Date parking end</th>
        <th>Patente</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    
    <tbody>
      <% @events.each do |event| %>
      <tr>
        <td><%= "#{event.lot.lot_row}""#{event.lot.lot_column}" %></td>
        <td><%= event.date_parking_start %></td>
        <td><%= event.date_parking_end %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to 'New Event', new_lot_event_path %>
<div class="container" id="calendar"></div>
<br>


<div class="modal fade">
  <div class="modal-dialog" role="document">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal"aria-label="Close">
              <span aria-hidden="true">&times;</span>
              </button>
          </div>
          <div class="modal-body">
              <p> </p>
          </div>
      </div>
  </div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', lot_events_path %>

app/views/events/new.js.erb
$('.modal').modal('show')
$('.modal-body').html("<%= j render 'form', event: @event%>")
$('.modal-content').on('focusin','.datepicker', function(){
    <!-- $(this).datetimepicker -->

    var f = new Date();
    $('#init_date_picker').datetimepicker({
        minView: 2,
        format: 'dd-MM-yyyy',
        autoclose: true,
        language: 'es',
        weekStart: 1,
        startDate: f,
        icons: {
            time: 'fa fa-clock-o',
            date: 'fa fa-calendar',
            up: 'fa fa-chevron-up',
            down: 'fa fa-chevron-down',
            previous: 'fa fa-chevron-left',
            next: 'fa fa-chevron-right',
            today: 'glyphicon glyphicon-screenshot',
            clear: 'fa fa-trash',
            close: 'fa fa-times'
        }
    })

    $('#end_date_picker').datetimepicker({
        useCurrent: false, //Important! See issue #1075
        minView: 2,
        format: 'dd-MM-yyyy',
        autoclose: true,
        language: 'es',
        weekStart: 1,
        startDate: f,
        icons: {
            time: 'fa fa-clock-o',
            date: 'far fa-calendar-alt',
            up: 'fa fa-arrow-up',
            down: 'fa fa-arrow-down'
            }
    });

    
    $("#init_date_picker").on("changeDate", function (e) {
        $('#end_date_picker').datetimepicker('setStartDate',$("#init_date_picker").val());
    });

    $("#end_date_picker").on("changeDate", function (e) {
        $('#init_date_picker').datetimepicker('setEndDate',$("#end_date_picker").val());
    });
})

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lot:</strong>
  <%= @event.lot %>
</p>

<p>
  <strong>Date parking start:</strong>
  <%= @event.date_parking_start %>
</p>

<p>
  <strong>Date parking end:</strong>
  <%= @event.date_parking_end %>
</p>

<p>
  <strong>Car:</strong>
  <%= @event.car %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>