config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  resources :tickets
  resources :lots do
    resources :events
  end
  resources :cars
  
  get 'billings/pre_pay', to:'billings#pre_pay', as: 'pre_pay_billings'
  get 'billings/execute', to:'billings#execute', as:'execute_billings'
  
  root 'tickets#new'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :car
  belongs_to :billing, optional: true
  has_many :events
  accepts_nested_attributes_for :events, allow_destroy: true
 
  scope :cart, (-> {where(payed: false)})


  def self.to_paypal_items
    where(nil).map do |ticket|
      item = {}
      item[:name] = ticket.date_parking_start
      item[:sku] = ticket.id.to_s
      item[:price] = ticket.total
      item[:currency] = 'USD'
      item[:quantity] = 1
      item
    end
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
    @ticket.events.build
    @price = 5900
  
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to pre_pay_billings_path }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:car_id, :total, events_attributes:[:lot_id, :date_parking_start, :date_parking_end])
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true , class: "container") do |form|%>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group align-items-center">
    <%= form.label :Selecciona_tu_automovil , class:"label-lg pr-2" %>
    <%= form.select :car_id, options_for_select(current_user.cars.map{|s|[s.plate,s.id]}),{class: 'selectpicker'}%>
  </div>

  <%= form.fields_for :events do |events_form| %>
    <%= render 'events/events_fields', events_form: events_form %>
  <%end %>


  <div class="form-group">
    <%= form.label :total %>
    <%= form.number_field :total %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Car</th>
      <th>Date parking start</th>
      <th>Date parking end</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.car.plate %></td>
        <td><%= ticket.date_parking_start %></td>
        <td><%= ticket.date_parking_end %></td>
        <td><%= ticket.total %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= button_to 'Destroy', ticket, method: :delete, remote: true,data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>


<div id="calendar" class="container"></div>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Car:</strong>
  <%= @ticket.car.plate %>
</p>

<p>
  <strong>Date parking start:</strong>
  <%= @ticket.date_parking_start %>
</p>

<p>
  <strong>Date parking end:</strong>
  <%= @ticket.date_parking_end %>
</p>

<p>
  <strong>Total:</strong>
  <%= @ticket.total %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>