config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  resources :tickets
  resources :lots do
    resources :events
  end
  resources :cars
  
  get 'billings/pre_pay', to:'billings#pre_pay', as: 'pre_pay_billings'
  get 'billings/execute', to:'billings#execute', as:'execute_billings'
  
  root 'tickets#new'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lot.rb
class Lot < ApplicationRecord
    has_many :events

    def parking_lot
        "#{lot_row} #{lot_column}"
    end

    def val_lot
        "#{id}"
    end
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
  before_action :set_lot, only: [:show, :edit, :update, :destroy]

  # GET /lots
  # GET /lots.json
  def index
    @lots = Lot.all
  end

  # GET /lots/1
  # GET /lots/1.json
  def show
  end

  # GET /lots/new
  def new
    @lot = Lot.new
  end

  # GET /lots/1/edit
  def edit
  end

  # POST /lots
  # POST /lots.json
  def create
    @lot = Lot.new(lot_params)

    respond_to do |format|
      if @lot.save
        format.html { redirect_to @lot, notice: 'Lot was successfully created.' }
        format.json { render :show, status: :created, location: @lot }
      else
        format.html { render :new }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lots/1
  # PATCH/PUT /lots/1.json
  def update
    respond_to do |format|
      if @lot.update(lot_params)
        format.html { redirect_to @lot, notice: 'Lot was successfully updated.' }
        format.json { render :show, status: :ok, location: @lot }
      else
        format.html { render :edit }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lots/1
  # DELETE /lots/1.json
  def destroy
    @lot.destroy
    respond_to do |format|
      format.html { redirect_to lots_url, notice: 'Lot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lot
      @lot = Lot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lot_params
      params.require(:lot).permit(:lot_column, :lot_row)
    end
end

app/helpers/lots_helper.rb
module LotsHelper
end

app/views/lots/_form.html.erb
<%= form_with(model: lot, local: true) do |form| %>
  <% if lot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lot.errors.count, "error") %> prohibited this lot from being saved:</h2>

      <ul>
      <% lot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lot_column %>
    <%= form.text_field :lot_column %>
  </div>

  <div class="field">
    <%= form.label :lot_row %>
    <%= form.number_field :lot_row %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lots/edit.html.erb
<h1>Editing Lot</h1>

<%= render 'form', lot: @lot %>

<%= link_to 'Show', @lot %> |
<%= link_to 'Back', lots_path %>

app/views/lots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lots</h1>

<!-- <table>
  <thead>
    <tr>
      <th>Lot column</th>
      <th>Lot row</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lots.each do |lot| %>
      <tr>
        <td><%= lot.lot_column %></td>
        <td><%= lot.lot_row %></td>
        <td><%= link_to 'Show', lot %></td>
        <td><%= link_to 'Edit', edit_lot_path(lot) %></td>
        <td><%= link_to 'Destroy', lot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lot', new_lot_path %> -->

<div id="map-container"></div>
<div id="legend-container"></div>
<div id="shoppingCart-container"></div>

app/views/lots/new.html.erb
<h1>New Lot</h1>

<%= render 'form', lot: @lot %>

<%= link_to 'Back', lots_path %>

app/views/lots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lot column:</strong>
  <%= @lot.lot_column %>
</p>

<p>
  <strong>Lot row:</strong>
  <%= @lot.lot_row %>
</p>

<%= link_to 'Edit', edit_lot_path(@lot) %> |
<%= link_to 'Back', lots_path %>